#!/usr/bin/env python3
"""Regenerate proto.h from the sketch. The Arduino build creates these
declarations automatically; a plain g++ build does not, and the sketch calls
plenty of functions before defining them."""
import re, sys
src = open(sys.argv[1]).read()
# top-level "type name(args) {" at column 0. 'static' functions are skipped:
# they are file-local and in this sketch always defined before first use.
pat = re.compile(r'^((?:const\s+)?[A-Za-z_][A-Za-z0-9_]*(?:\s*\*+)?)\s+'
                 r'(\*?[A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*\{', re.M)
skip = {'if','for','while','switch','else','do','return','struct','class','enum','static'}
protos, seen = [], set()
for m in pat.finditer(src):
    ret, name, args = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    if ret in skip or name in seen or name in ('setup','loop'):
        continue
    seen.add(name)
    protos.append(f"{ret} {name}({args});")
open('proto.h','w').write(
    "// GENERATED by genproto.py at build time - do not edit\n#pragma once\n"
    '#include "Arduino.h"\n#include "Arduino_GFX_Library.h"\n#include "sdmon.h"\n'
    '#include "species.h"\n#include "dex.h"\n#include "types.h"\n#include "party.h"\n'
    '#include "pet.h"\n\n' + "\n".join(protos) + "\n")
print(f"proto.h: {len(protos)} declarations")
