# -*- coding: utf-8 -*-
"""Typings and the type effectiveness chart, CURRENT (Gen 6+) rules.

Deliberately not the Gen 1 chart, even though the rest of the game is Gen 1
flavoured. Three reasons: the Gen 1 chart shipped real bugs (Ghost moves did
nothing at all to Psychic), Psychic was resisted only by Psychic and so ran
away with every battle, and -- decisively -- the base stats in dex_stats.py
were already pulled from PokeAPI at their CURRENT values, not their Gen 1 ones
(Pidgeot has 101 Speed here, not the 91 it had in Red/Blue). Modern stats with
an ancient chart is the inconsistent combination; this makes the data cohere.

Fairy also earns its place: Dragonite has the highest Attack in the dex, and
under pre-Gen-6 rules Dragon is resisted only by Steel. Dragon -> Fairy is 0x,
which hands the player a real answer to the strongest thing they can hatch.

Consumed by gen_dex.py, which emits dex.h.
"""

# Order matters: it is the index order of the effectiveness matrix and of the
# PkType enum in dex.h.
TYPE_ORDER = [
    'normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting',
    'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost',
    'dragon', 'dark', 'steel', 'fairy',
]

# Attacker -> {defender: multiplier}. Anything unlisted is 1x.
# Current (Gen 6+) chart. Note Steel lost its Dark and Ghost resistances in
# Gen 6, so those cells are neutral here and not 0.5x.
CHART = {
    'normal':   {'rock': .5, 'ghost': 0, 'steel': .5},
    'fire':     {'fire': .5, 'water': .5, 'grass': 2, 'ice': 2, 'bug': 2,
                 'rock': .5, 'dragon': .5, 'steel': 2},
    'water':    {'fire': 2, 'water': .5, 'grass': .5, 'ground': 2, 'rock': 2,
                 'dragon': .5},
    'electric': {'water': 2, 'electric': .5, 'grass': .5, 'ground': 0,
                 'flying': 2, 'dragon': .5},
    'grass':    {'fire': .5, 'water': 2, 'grass': .5, 'poison': .5, 'ground': 2,
                 'flying': .5, 'bug': .5, 'rock': 2, 'dragon': .5, 'steel': .5},
    'ice':      {'fire': .5, 'water': .5, 'grass': 2, 'ice': .5, 'ground': 2,
                 'flying': 2, 'dragon': 2, 'steel': .5},
    'fighting': {'normal': 2, 'ice': 2, 'poison': .5, 'flying': .5,
                 'psychic': .5, 'bug': .5, 'rock': 2, 'ghost': 0, 'dark': 2,
                 'steel': 2, 'fairy': .5},
    'poison':   {'grass': 2, 'poison': .5, 'ground': .5, 'rock': .5,
                 'ghost': .5, 'steel': 0, 'fairy': 2},
    'ground':   {'fire': 2, 'electric': 2, 'grass': .5, 'poison': 2,
                 'flying': 0, 'bug': .5, 'rock': 2, 'steel': 2},
    'flying':   {'electric': .5, 'grass': 2, 'fighting': 2, 'bug': 2,
                 'rock': .5, 'steel': .5},
    'psychic':  {'fighting': 2, 'poison': 2, 'psychic': .5, 'dark': 0,
                 'steel': .5},
    'bug':      {'fire': .5, 'grass': 2, 'fighting': .5, 'poison': .5,
                 'flying': .5, 'psychic': 2, 'ghost': .5, 'dark': 2,
                 'steel': .5, 'fairy': .5},
    'rock':     {'fire': 2, 'ice': 2, 'fighting': .5, 'ground': .5,
                 'flying': 2, 'bug': 2, 'steel': .5},
    'ghost':    {'normal': 0, 'psychic': 2, 'ghost': 2, 'dark': .5},
    'dragon':   {'dragon': 2, 'steel': .5, 'fairy': 0},
    'dark':     {'fighting': .5, 'psychic': 2, 'ghost': 2, 'dark': .5,
                 'fairy': .5},
    'steel':    {'fire': .5, 'water': .5, 'electric': .5, 'ice': 2, 'rock': 2,
                 'steel': .5, 'fairy': 2},
    'fairy':    {'fire': .5, 'fighting': 2, 'poison': .5, 'dragon': 2,
                 'dark': 2, 'steel': .5},
}

# Typing of the 151 under current (Gen 6+) rules. Seven differ from Gen 1:
# Magnemite/Magneton gained Steel in Gen 2, and Clefairy, Clefable, Jigglypuff,
# Wigglytuff and Mr. Mime gained Fairy in Gen 6 (the first two becoming PURE
# Fairy, losing Normal entirely).
TYPES = {
    1: ('grass', 'poison'), 2: ('grass', 'poison'), 3: ('grass', 'poison'),
    4: ('fire', None), 5: ('fire', None), 6: ('fire', 'flying'),
    7: ('water', None), 8: ('water', None), 9: ('water', None),
    10: ('bug', None), 11: ('bug', None), 12: ('bug', 'flying'),
    13: ('bug', 'poison'), 14: ('bug', 'poison'), 15: ('bug', 'poison'),
    16: ('normal', 'flying'), 17: ('normal', 'flying'), 18: ('normal', 'flying'),
    19: ('normal', None), 20: ('normal', None),
    21: ('normal', 'flying'), 22: ('normal', 'flying'),
    23: ('poison', None), 24: ('poison', None),
    25: ('electric', None), 26: ('electric', None),
    27: ('ground', None), 28: ('ground', None),
    29: ('poison', None), 30: ('poison', None), 31: ('poison', 'ground'),
    32: ('poison', None), 33: ('poison', None), 34: ('poison', 'ground'),
    35: ('fairy', None), 36: ('fairy', None),  # pure Fairy from Gen 6
    37: ('fire', None), 38: ('fire', None),
    39: ('normal', 'fairy'), 40: ('normal', 'fairy'),
    41: ('poison', 'flying'), 42: ('poison', 'flying'),
    43: ('grass', 'poison'), 44: ('grass', 'poison'), 45: ('grass', 'poison'),
    46: ('bug', 'grass'), 47: ('bug', 'grass'),
    48: ('bug', 'poison'), 49: ('bug', 'poison'),
    50: ('ground', None), 51: ('ground', None),
    52: ('normal', None), 53: ('normal', None),
    54: ('water', None), 55: ('water', None),
    56: ('fighting', None), 57: ('fighting', None),
    58: ('fire', None), 59: ('fire', None),
    60: ('water', None), 61: ('water', None), 62: ('water', 'fighting'),
    63: ('psychic', None), 64: ('psychic', None), 65: ('psychic', None),
    66: ('fighting', None), 67: ('fighting', None), 68: ('fighting', None),
    69: ('grass', 'poison'), 70: ('grass', 'poison'), 71: ('grass', 'poison'),
    72: ('water', 'poison'), 73: ('water', 'poison'),
    74: ('rock', 'ground'), 75: ('rock', 'ground'), 76: ('rock', 'ground'),
    77: ('fire', None), 78: ('fire', None),
    79: ('water', 'psychic'), 80: ('water', 'psychic'),
    81: ('electric', 'steel'), 82: ('electric', 'steel'),  # Steel from Gen 2
    83: ('normal', 'flying'), 84: ('normal', 'flying'), 85: ('normal', 'flying'),
    86: ('water', None), 87: ('water', 'ice'),
    88: ('poison', None), 89: ('poison', None),
    90: ('water', None), 91: ('water', 'ice'),
    92: ('ghost', 'poison'), 93: ('ghost', 'poison'), 94: ('ghost', 'poison'),
    95: ('rock', 'ground'),
    96: ('psychic', None), 97: ('psychic', None),
    98: ('water', None), 99: ('water', None),
    100: ('electric', None), 101: ('electric', None),
    102: ('grass', 'psychic'), 103: ('grass', 'psychic'),
    104: ('ground', None), 105: ('ground', None),
    106: ('fighting', None), 107: ('fighting', None),
    108: ('normal', None),
    109: ('poison', None), 110: ('poison', None),
    111: ('ground', 'rock'), 112: ('ground', 'rock'),
    113: ('normal', None), 114: ('grass', None), 115: ('normal', None),
    116: ('water', None), 117: ('water', None),
    118: ('water', None), 119: ('water', None),
    120: ('water', None), 121: ('water', 'psychic'),
    122: ('psychic', 'fairy'),
    123: ('bug', 'flying'), 124: ('ice', 'psychic'),
    125: ('electric', None), 126: ('fire', None), 127: ('bug', None),
    128: ('normal', None), 129: ('water', None), 130: ('water', 'flying'),
    131: ('water', 'ice'), 132: ('normal', None), 133: ('normal', None),
    134: ('water', None), 135: ('electric', None), 136: ('fire', None),
    137: ('normal', None),
    138: ('rock', 'water'), 139: ('rock', 'water'),
    140: ('rock', 'water'), 141: ('rock', 'water'),
    142: ('rock', 'flying'), 143: ('normal', None),
    144: ('ice', 'flying'), 145: ('electric', 'flying'), 146: ('fire', 'flying'),
    147: ('dragon', None), 148: ('dragon', None), 149: ('dragon', 'flying'),
    150: ('psychic', None), 151: ('psychic', None),
    # --- generated by gen_dex_data.py
    152: ('grass', None),
    153: ('grass', None),
    154: ('grass', None),
    155: ('fire', None),
    156: ('fire', None),
    157: ('fire', None),
    158: ('water', None),
    159: ('water', None),
    160: ('water', None),
    161: ('normal', None),
    162: ('normal', None),
    163: ('normal', 'flying'),
    164: ('normal', 'flying'),
    165: ('bug', 'flying'),
    166: ('bug', 'flying'),
    167: ('bug', 'poison'),
    168: ('bug', 'poison'),
    169: ('poison', 'flying'),
    170: ('water', 'electric'),
    171: ('water', 'electric'),
    172: ('electric', None),
    173: ('fairy', None),
    174: ('normal', 'fairy'),
    175: ('fairy', None),
    176: ('fairy', 'flying'),
    177: ('psychic', 'flying'),
    178: ('psychic', 'flying'),
    179: ('electric', None),
    180: ('electric', None),
    181: ('electric', None),
    182: ('grass', None),
    183: ('water', 'fairy'),
    184: ('water', 'fairy'),
    185: ('rock', None),
    186: ('water', None),
    187: ('grass', 'flying'),
    188: ('grass', 'flying'),
    189: ('grass', 'flying'),
    190: ('normal', None),
    191: ('grass', None),
    192: ('grass', None),
    193: ('bug', 'flying'),
    194: ('water', 'ground'),
    195: ('water', 'ground'),
    196: ('psychic', None),
    197: ('dark', None),
    198: ('dark', 'flying'),
    199: ('water', 'psychic'),
    200: ('ghost', None),
    201: ('psychic', None),
    202: ('psychic', None),
    203: ('normal', 'psychic'),
    204: ('bug', None),
    205: ('bug', 'steel'),
    206: ('normal', None),
    207: ('ground', 'flying'),
    208: ('steel', 'ground'),
    209: ('fairy', None),
    210: ('fairy', None),
    211: ('water', 'poison'),
    212: ('bug', 'steel'),
    213: ('bug', 'rock'),
    214: ('bug', 'fighting'),
    215: ('dark', 'ice'),
    216: ('normal', None),
    217: ('normal', None),
    218: ('fire', None),
    219: ('fire', 'rock'),
    220: ('ice', 'ground'),
    221: ('ice', 'ground'),
    222: ('water', 'rock'),
    223: ('water', None),
    224: ('water', None),
    225: ('ice', 'flying'),
    226: ('water', 'flying'),
    227: ('steel', 'flying'),
    228: ('dark', 'fire'),
    229: ('dark', 'fire'),
    230: ('water', 'dragon'),
    231: ('ground', None),
    232: ('ground', None),
    233: ('normal', None),
    234: ('normal', None),
    235: ('normal', None),
    236: ('fighting', None),
    237: ('fighting', None),
    238: ('ice', 'psychic'),
    239: ('electric', None),
    240: ('fire', None),
    241: ('normal', None),
    242: ('normal', None),
    243: ('electric', None),
    244: ('fire', None),
    245: ('water', None),
    246: ('rock', 'ground'),
    247: ('rock', 'ground'),
    248: ('rock', 'dark'),
    249: ('psychic', 'flying'),
    250: ('fire', 'flying'),
    251: ('psychic', 'grass'),
    252: ('grass', None),
    253: ('grass', None),
    254: ('grass', None),
    255: ('fire', None),
    256: ('fire', 'fighting'),
    257: ('fire', 'fighting'),
    258: ('water', None),
    259: ('water', 'ground'),
    260: ('water', 'ground'),
    261: ('dark', None),
    262: ('dark', None),
    263: ('normal', None),
    264: ('normal', None),
    265: ('bug', None),
    266: ('bug', None),
    267: ('bug', 'flying'),
    268: ('bug', None),
    269: ('bug', 'poison'),
    270: ('water', 'grass'),
    271: ('water', 'grass'),
    272: ('water', 'grass'),
    273: ('grass', None),
    274: ('grass', 'dark'),
    275: ('grass', 'dark'),
    276: ('normal', 'flying'),
    277: ('normal', 'flying'),
    278: ('water', 'flying'),
    279: ('water', 'flying'),
    280: ('psychic', 'fairy'),
    281: ('psychic', 'fairy'),
    282: ('psychic', 'fairy'),
    283: ('bug', 'water'),
    284: ('bug', 'flying'),
    285: ('grass', None),
    286: ('grass', 'fighting'),
    287: ('normal', None),
    288: ('normal', None),
    289: ('normal', None),
    290: ('bug', 'ground'),
    291: ('bug', 'flying'),
    292: ('bug', 'ghost'),
    293: ('normal', None),
    294: ('normal', None),
    295: ('normal', None),
    296: ('fighting', None),
    297: ('fighting', None),
    298: ('normal', 'fairy'),
    299: ('rock', None),
    300: ('normal', None),
    301: ('normal', None),
    302: ('dark', 'ghost'),
    303: ('steel', 'fairy'),
    304: ('steel', 'rock'),
    305: ('steel', 'rock'),
    306: ('steel', 'rock'),
    307: ('fighting', 'psychic'),
    308: ('fighting', 'psychic'),
    309: ('electric', None),
    310: ('electric', None),
    311: ('electric', None),
    312: ('electric', None),
    313: ('bug', None),
    314: ('bug', None),
    315: ('grass', 'poison'),
    316: ('poison', None),
    317: ('poison', None),
    318: ('water', 'dark'),
    319: ('water', 'dark'),
    320: ('water', None),
    321: ('water', None),
    322: ('fire', 'ground'),
    323: ('fire', 'ground'),
    324: ('fire', None),
    325: ('psychic', None),
    326: ('psychic', None),
    327: ('normal', None),
    328: ('ground', None),
    329: ('ground', 'dragon'),
    330: ('ground', 'dragon'),
    331: ('grass', None),
    332: ('grass', 'dark'),
    333: ('normal', 'flying'),
    334: ('dragon', 'flying'),
    335: ('normal', None),
    336: ('poison', None),
    337: ('rock', 'psychic'),
    338: ('rock', 'psychic'),
    339: ('water', 'ground'),
    340: ('water', 'ground'),
    341: ('water', None),
    342: ('water', 'dark'),
    343: ('ground', 'psychic'),
    344: ('ground', 'psychic'),
    345: ('rock', 'grass'),
    346: ('rock', 'grass'),
    347: ('rock', 'bug'),
    348: ('rock', 'bug'),
    349: ('water', None),
    350: ('water', None),
    351: ('normal', None),
    352: ('normal', None),
    353: ('ghost', None),
    354: ('ghost', None),
    355: ('ghost', None),
    356: ('ghost', None),
    357: ('grass', 'flying'),
    358: ('psychic', None),
    359: ('dark', None),
    360: ('psychic', None),
    361: ('ice', None),
    362: ('ice', None),
    363: ('ice', 'water'),
    364: ('ice', 'water'),
    365: ('ice', 'water'),
    366: ('water', None),
    367: ('water', None),
    368: ('water', None),
    369: ('water', 'rock'),
    370: ('water', None),
    371: ('dragon', None),
    372: ('dragon', None),
    373: ('dragon', 'flying'),
    374: ('steel', 'psychic'),
    375: ('steel', 'psychic'),
    376: ('steel', 'psychic'),
    377: ('rock', None),
    378: ('ice', None),
    379: ('steel', None),
    380: ('dragon', 'psychic'),
    381: ('dragon', 'psychic'),
    382: ('water', None),
    383: ('ground', None),
    384: ('dragon', 'flying'),
    385: ('steel', 'psychic'),
    386: ('psychic', None),
    387: ('grass', None),
    388: ('grass', None),
    389: ('grass', 'ground'),
    390: ('fire', None),
    391: ('fire', 'fighting'),
    392: ('fire', 'fighting'),
    393: ('water', None),
    394: ('water', None),
    395: ('water', 'steel'),
    396: ('normal', 'flying'),
    397: ('normal', 'flying'),
    398: ('normal', 'flying'),
    399: ('normal', None),
    400: ('normal', 'water'),
    401: ('bug', None),
    402: ('bug', None),
    403: ('electric', None),
    404: ('electric', None),
    405: ('electric', None),
    406: ('grass', 'poison'),
    407: ('grass', 'poison'),
    408: ('rock', None),
    409: ('rock', None),
    410: ('rock', 'steel'),
    411: ('rock', 'steel'),
    412: ('bug', None),
    413: ('bug', 'grass'),
    414: ('bug', 'flying'),
    415: ('bug', 'flying'),
    416: ('bug', 'flying'),
    417: ('electric', None),
    418: ('water', None),
    419: ('water', None),
    420: ('grass', None),
    421: ('grass', None),
    422: ('water', None),
    423: ('water', 'ground'),
    424: ('normal', None),
    425: ('ghost', 'flying'),
    426: ('ghost', 'flying'),
    427: ('normal', None),
    428: ('normal', None),
    429: ('ghost', None),
    430: ('dark', 'flying'),
    431: ('normal', None),
    432: ('normal', None),
    433: ('psychic', None),
    434: ('poison', 'dark'),
    435: ('poison', 'dark'),
    436: ('steel', 'psychic'),
    437: ('steel', 'psychic'),
    438: ('rock', None),
    439: ('psychic', 'fairy'),
    440: ('normal', None),
    441: ('normal', 'flying'),
    442: ('ghost', 'dark'),
    443: ('dragon', 'ground'),
    444: ('dragon', 'ground'),
    445: ('dragon', 'ground'),
    446: ('normal', None),
    447: ('fighting', None),
    448: ('fighting', 'steel'),
    449: ('ground', None),
    450: ('ground', None),
    451: ('poison', 'bug'),
    452: ('poison', 'dark'),
    453: ('poison', 'fighting'),
    454: ('poison', 'fighting'),
    455: ('grass', None),
    456: ('water', None),
    457: ('water', None),
    458: ('water', 'flying'),
    459: ('grass', 'ice'),
    460: ('grass', 'ice'),
    461: ('dark', 'ice'),
    462: ('electric', 'steel'),
    463: ('normal', None),
    464: ('ground', 'rock'),
    465: ('grass', None),
    466: ('electric', None),
    467: ('fire', None),
    468: ('fairy', 'flying'),
    469: ('bug', 'flying'),
    470: ('grass', None),
    471: ('ice', None),
    472: ('ground', 'flying'),
    473: ('ice', 'ground'),
    474: ('normal', None),
    475: ('psychic', 'fighting'),
    476: ('rock', 'steel'),
    477: ('ghost', None),
    478: ('ice', 'ghost'),
    479: ('electric', 'ghost'),
    480: ('psychic', None),
    481: ('psychic', None),
    482: ('psychic', None),
    483: ('steel', 'dragon'),
    484: ('water', 'dragon'),
    485: ('fire', 'steel'),
    486: ('normal', None),
    487: ('ghost', 'dragon'),
    488: ('psychic', None),
    489: ('water', None),
    490: ('water', None),
    491: ('dark', None),
    492: ('grass', None),
    493: ('normal', None),
    494: ('psychic', 'fire'),
    495: ('grass', None),
    496: ('grass', None),
    497: ('grass', None),
    498: ('fire', None),
    499: ('fire', 'fighting'),
    500: ('fire', 'fighting'),
    501: ('water', None),
    502: ('water', None),
    503: ('water', None),
    504: ('normal', None),
    505: ('normal', None),
    506: ('normal', None),
    507: ('normal', None),
    508: ('normal', None),
    509: ('dark', None),
    510: ('dark', None),
    511: ('grass', None),
    512: ('grass', None),
    513: ('fire', None),
    514: ('fire', None),
    515: ('water', None),
    516: ('water', None),
    517: ('psychic', None),
    518: ('psychic', None),
    519: ('normal', 'flying'),
    520: ('normal', 'flying'),
    521: ('normal', 'flying'),
    522: ('electric', None),
    523: ('electric', None),
    524: ('rock', None),
    525: ('rock', None),
    526: ('rock', None),
    527: ('psychic', 'flying'),
    528: ('psychic', 'flying'),
    529: ('ground', None),
    530: ('ground', 'steel'),
    531: ('normal', None),
    532: ('fighting', None),
    533: ('fighting', None),
    534: ('fighting', None),
    535: ('water', None),
    536: ('water', 'ground'),
    537: ('water', 'ground'),
    538: ('fighting', None),
    539: ('fighting', None),
    540: ('bug', 'grass'),
    541: ('bug', 'grass'),
    542: ('bug', 'grass'),
    543: ('bug', 'poison'),
    544: ('bug', 'poison'),
    545: ('bug', 'poison'),
    546: ('grass', 'fairy'),
    547: ('grass', 'fairy'),
    548: ('grass', None),
    549: ('grass', None),
    550: ('water', None),
    551: ('ground', 'dark'),
    552: ('ground', 'dark'),
    553: ('ground', 'dark'),
    554: ('fire', None),
    555: ('fire', None),
    556: ('grass', None),
    557: ('bug', 'rock'),
    558: ('bug', 'rock'),
    559: ('dark', 'fighting'),
    560: ('dark', 'fighting'),
    561: ('psychic', 'flying'),
    562: ('ghost', None),
    563: ('ghost', None),
    564: ('water', 'rock'),
    565: ('water', 'rock'),
    566: ('rock', 'flying'),
    567: ('rock', 'flying'),
    568: ('poison', None),
    569: ('poison', None),
    570: ('dark', None),
    571: ('dark', None),
    572: ('normal', None),
    573: ('normal', None),
    574: ('psychic', None),
    575: ('psychic', None),
    576: ('psychic', None),
    577: ('psychic', None),
    578: ('psychic', None),
    579: ('psychic', None),
    580: ('water', 'flying'),
    581: ('water', 'flying'),
    582: ('ice', None),
    583: ('ice', None),
    584: ('ice', None),
    585: ('normal', 'grass'),
    586: ('normal', 'grass'),
    587: ('electric', 'flying'),
    588: ('bug', None),
    589: ('bug', 'steel'),
    590: ('grass', 'poison'),
    591: ('grass', 'poison'),
    592: ('water', 'ghost'),
    593: ('water', 'ghost'),
    594: ('water', None),
    595: ('bug', 'electric'),
    596: ('bug', 'electric'),
    597: ('grass', 'steel'),
    598: ('grass', 'steel'),
    599: ('steel', None),
    600: ('steel', None),
    601: ('steel', None),
    602: ('electric', None),
    603: ('electric', None),
    604: ('electric', None),
    605: ('psychic', None),
    606: ('psychic', None),
    607: ('ghost', 'fire'),
    608: ('ghost', 'fire'),
    609: ('ghost', 'fire'),
    610: ('dragon', None),
    611: ('dragon', None),
    612: ('dragon', None),
    613: ('ice', None),
    614: ('ice', None),
    615: ('ice', None),
    616: ('bug', None),
    617: ('bug', None),
    618: ('ground', 'electric'),
    619: ('fighting', None),
    620: ('fighting', None),
    621: ('dragon', None),
    622: ('ground', 'ghost'),
    623: ('ground', 'ghost'),
    624: ('dark', 'steel'),
    625: ('dark', 'steel'),
    626: ('normal', None),
    627: ('normal', 'flying'),
    628: ('normal', 'flying'),
    629: ('dark', 'flying'),
    630: ('dark', 'flying'),
    631: ('fire', None),
    632: ('bug', 'steel'),
    633: ('dark', 'dragon'),
    634: ('dark', 'dragon'),
    635: ('dark', 'dragon'),
    636: ('bug', 'fire'),
    637: ('bug', 'fire'),
    638: ('steel', 'fighting'),
    639: ('rock', 'fighting'),
    640: ('grass', 'fighting'),
    641: ('flying', None),
    642: ('electric', 'flying'),
    643: ('dragon', 'fire'),
    644: ('dragon', 'electric'),
    645: ('ground', 'flying'),
    646: ('dragon', 'ice'),
    647: ('water', 'fighting'),
    648: ('normal', 'psychic'),
    649: ('bug', 'steel'),
    650: ('grass', None),
    651: ('grass', None),
    652: ('grass', 'fighting'),
    653: ('fire', None),
    654: ('fire', None),
    655: ('fire', 'psychic'),
    656: ('water', None),
    657: ('water', None),
    658: ('water', 'dark'),
    659: ('normal', None),
    660: ('normal', 'ground'),
    661: ('normal', 'flying'),
    662: ('fire', 'flying'),
    663: ('fire', 'flying'),
    664: ('bug', None),
    665: ('bug', None),
    666: ('bug', 'flying'),
    667: ('fire', 'normal'),
    668: ('fire', 'normal'),
    669: ('fairy', None),
    670: ('fairy', None),
    671: ('fairy', None),
    672: ('grass', None),
    673: ('grass', None),
    674: ('fighting', None),
    675: ('fighting', 'dark'),
    676: ('normal', None),
    677: ('psychic', None),
    678: ('psychic', None),
    679: ('steel', 'ghost'),
    680: ('steel', 'ghost'),
    681: ('steel', 'ghost'),
    682: ('fairy', None),
    683: ('fairy', None),
    684: ('fairy', None),
    685: ('fairy', None),
    686: ('dark', 'psychic'),
    687: ('dark', 'psychic'),
    688: ('rock', 'water'),
    689: ('rock', 'water'),
    690: ('poison', 'water'),
    691: ('poison', 'dragon'),
    692: ('water', None),
    693: ('water', None),
    694: ('electric', 'normal'),
    695: ('electric', 'normal'),
    696: ('rock', 'dragon'),
    697: ('rock', 'dragon'),
    698: ('rock', 'ice'),
    699: ('rock', 'ice'),
    700: ('fairy', None),
    701: ('fighting', 'flying'),
    702: ('electric', 'fairy'),
    703: ('rock', 'fairy'),
    704: ('dragon', None),
    705: ('dragon', None),
    706: ('dragon', None),
    707: ('steel', 'fairy'),
    708: ('ghost', 'grass'),
    709: ('ghost', 'grass'),
    710: ('ghost', 'grass'),
    711: ('ghost', 'grass'),
    712: ('ice', None),
    713: ('ice', None),
    714: ('flying', 'dragon'),
    715: ('flying', 'dragon'),
    716: ('fairy', None),
    717: ('dark', 'flying'),
    718: ('dragon', 'ground'),
    719: ('rock', 'fairy'),
    720: ('psychic', 'ghost'),
    721: ('fire', 'water'),
    722: ('grass', 'flying'),
    723: ('grass', 'flying'),
    724: ('grass', 'ghost'),
    725: ('fire', None),
    726: ('fire', None),
    727: ('fire', 'dark'),
    728: ('water', None),
    729: ('water', None),
    730: ('water', 'fairy'),
    731: ('normal', 'flying'),
    732: ('normal', 'flying'),
    733: ('normal', 'flying'),
    734: ('normal', None),
    735: ('normal', None),
    736: ('bug', None),
    737: ('bug', 'electric'),
    738: ('bug', 'electric'),
    739: ('fighting', None),
    740: ('fighting', 'ice'),
    741: ('fire', 'flying'),
    742: ('bug', 'fairy'),
    743: ('bug', 'fairy'),
    744: ('rock', None),
    745: ('rock', None),
    746: ('water', None),
    747: ('poison', 'water'),
    748: ('poison', 'water'),
    749: ('ground', None),
    750: ('ground', None),
    751: ('water', 'bug'),
    752: ('water', 'bug'),
    753: ('grass', None),
    754: ('grass', None),
    755: ('grass', 'fairy'),
    756: ('grass', 'fairy'),
    757: ('poison', 'fire'),
    758: ('poison', 'fire'),
    759: ('normal', 'fighting'),
    760: ('normal', 'fighting'),
    761: ('grass', None),
    762: ('grass', None),
    763: ('grass', None),
    764: ('fairy', None),
    765: ('normal', 'psychic'),
    766: ('fighting', None),
    767: ('bug', 'water'),
    768: ('bug', 'water'),
    769: ('ghost', 'ground'),
    770: ('ghost', 'ground'),
    771: ('water', None),
    772: ('normal', None),
    773: ('normal', None),
    774: ('rock', 'flying'),
    775: ('normal', None),
    776: ('fire', 'dragon'),
    777: ('electric', 'steel'),
    778: ('ghost', 'fairy'),
    779: ('water', 'psychic'),
    780: ('normal', 'dragon'),
    781: ('ghost', 'grass'),
    782: ('dragon', None),
    783: ('dragon', 'fighting'),
    784: ('dragon', 'fighting'),
    785: ('electric', 'fairy'),
    786: ('psychic', 'fairy'),
    787: ('grass', 'fairy'),
    788: ('water', 'fairy'),
    789: ('psychic', None),
    790: ('psychic', None),
    791: ('psychic', 'steel'),
    792: ('psychic', 'ghost'),
    793: ('rock', 'poison'),
    794: ('bug', 'fighting'),
    795: ('bug', 'fighting'),
    796: ('electric', None),
    797: ('steel', 'flying'),
    798: ('grass', 'steel'),
    799: ('dark', 'dragon'),
    800: ('psychic', None),
    801: ('steel', 'fairy'),
    802: ('fighting', 'ghost'),
    803: ('poison', None),
    804: ('poison', 'dragon'),
    805: ('rock', 'steel'),
    806: ('fire', 'ghost'),
    807: ('electric', None),
    808: ('steel', None),
    809: ('steel', None),
}
