#!/usr/bin/env python3
"""Player avatars: pret/pokered overworld sprites -> avatars.h

    python3 tools/gen_avatars.py

Downloads eight 16x16 overworld sprites from the pokered disassembly, takes the
first (front-facing) frame of each sheet and packs them 8bpp with a four-entry
RGB565 palette; index 0xFF is transparent.

The sheets are 2bpp greyscale, six frames stacked vertically. Shade 3 is the
white background and becomes transparent; 0 is the outline, 1 the large fill,
2 the highlight. Each avatar gets an accent colour on shade 1 -- the same thing
Pokemon Yellow did when it colourised these sprites for the GBC -- because eight
identical grey silhouettes are unreadable at a glance in the picker.

SOURCE AND LICENCE -- read CREDITS.md before publishing anything built from
this. These are Nintendo / Game Freak / Creatures artwork, taken from a
disassembly. They are NOT licensed for redistribution the way the PMD sprites
(CC BY-NC) or the badges (CC BY 3.0) are. They are here because the project
owner asked for the real sprites, and CREDITS.md records that honestly rather
than leaving it undocumented.
"""
import os
import struct
import sys
import subprocess
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'avatars.h')
BASE = 'https://raw.githubusercontent.com/pret/pokered/master/gfx/sprites/%s.png'
SIZE = 16

# (file, label shown in the UI, accent for shade 1)
# Eight, so the stored `avatar` byte still fits comfortably and cycling by tap
# stays short. Labels are unaccented ASCII: the bitmap font has nothing else.
PICKS = [
    ('red',           'RED',      0xEA87),   # the classic player
    ('blue',          'BLUE',     0x4C98),   # the rival
    ('girl',          'GIRL',     0xF454),
    ('cooltrainer_m', 'ACE M',    0x5DCD),
    ('cooltrainer_f', 'ACE F',    0xC2F0),
    ('hiker',         'HIKER',    0xB3C8),
    # NOT swimmer: it is drawn low in its cell (the character is in water),
    # which reads as a misaligned sprite once it is out of context.
    ('sailor',        'SAILOR',   0x7E3D),
    ('youngster',     'YOUNGSTER',0xFECB),
]

OUTLINE = 0x18C4     # same ink as the rest of the UI
HIGHLIGHT = 0xEF7D   # a soft off-white, so it reads on the cream card


def read_png_2bpp(data, path):
    """pokered's sprites are 2-bit greyscale; the shared decoder in
    gen_backs.py only handles 8-bit channels, so this one is separate."""
    pos, idat, w, h, bd, ct = 8, b'', 0, 0, 0, 0
    while pos < len(data):
        ln = struct.unpack('>I', data[pos:pos + 4])[0]
        typ = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + ln]
        if typ == b'IHDR':
            w, h, bd, ct = struct.unpack('>IIBB', chunk[:10])
        elif typ == b'IDAT':
            idat += chunk
        pos += 12 + ln
    if bd != 2 or ct != 0:
        raise SystemExit('%s: expected 2-bit greyscale, got bd=%d ct=%d'
                         % (path, bd, ct))
    raw = zlib.decompress(idat)
    bpr = (w * bd + 7) // 8
    rows, prev, i = [], bytearray(bpr), 0
    for _ in range(h):
        f = raw[i]; i += 1
        line = bytearray(raw[i:i + bpr]); i += bpr
        for x in range(len(line)):
            a = line[x - 1] if x >= 1 else 0
            b = prev[x]
            c = prev[x - 1] if x >= 1 else 0
            if f == 1:   line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 255
        rows.append(bytes(line)); prev = line
    px = []
    for line in rows:
        px.append([(line[x // 4] >> ((3 - (x % 4)) * 2)) & 3 for x in range(w)])
    return w, h, px


def main():
    out = ['// GENERATED by tools/gen_avatars.py from pret/pokered - do not edit',
           '#pragma once',
           '#include <stdint.h>',
           '',
           '// Player avatars: Gen 1 overworld sprites, 16x16, 8bpp indexed with',
           '// a four-entry RGB565 palette. Index 0xFF is transparent.',
           '//',
           '// See CREDITS.md: this is Nintendo / Game Freak artwork from a',
           '// disassembly, not licensed material like the PMD sprites are.',
           '']
    names = []
    for fn, label, accent in PICKS:
        url = BASE % fn
        sys.stderr.write('fetching %s\n' % url)
        # curl rather than urllib: the stock python.org build on macOS ships
        # without a usable CA bundle and fails to verify github.com.
        r = subprocess.run(['curl', '-fsSL', url], capture_output=True)
        if r.returncode != 0:
            raise SystemExit('fetch failed (%s): %s'
                             % (url, r.stderr.decode().strip()))
        data = r.stdout
        w, h, px = read_png_2bpp(data, fn)
        if w != SIZE or h % SIZE:
            raise SystemExit('%s: expected a %dpx-wide sheet, got %dx%d'
                             % (fn, SIZE, w, h))
        pal = [OUTLINE, accent, HIGHLIGHT]
        idx = []
        for y in range(SIZE):                 # frame 0 only: front-facing
            for x in range(SIZE):
                v = px[y][x]
                idx.append(0xFF if v == 3 else v)   # 3 = white = transparent
        sym = 'AV_' + fn.upper()
        names.append((sym, label))
        out.append('static const uint16_t %s_PAL[3] = { %s };'
                   % (sym, ', '.join('0x%04X' % c for c in pal)))
        out.append('static const uint8_t %s_IDX[%d] = {' % (sym, SIZE * SIZE))
        for r in range(SIZE):
            row = idx[r * SIZE:(r + 1) * SIZE]
            out.append('  ' + ' '.join('0x%02X,' % v for v in row))
        out.append('};')
        out.append('')

    out.append('struct AvatarArt {')
    out.append('  const uint8_t *idx;')
    out.append('  const uint16_t *pal;')
    out.append('  const char *name;')
    out.append('};')
    out.append('#define AVATAR_PX %d' % SIZE)
    out.append('#define AVATAR_COUNT %d' % len(names))
    out.append('static const AvatarArt AVATARS[AVATAR_COUNT] = {')
    for (sym, label), (fn, _, _) in zip(names, PICKS):
        out.append('  { %s_IDX, %s_PAL, "%s" },   // %s' % (sym, sym, label, fn))
    out.append('};')
    out.append('')
    open(OUT, 'w').write('\n'.join(out))
    sys.stderr.write('wrote %s (%d avatars)\n' % (OUT, len(names)))


if __name__ == '__main__':
    main()
